# Team members:
# 1. Anusha Gurram – G01514835
# 2. Bala Naga Tirumala Kiran Annadata – G01508483
# 3. Yashwanth Karthikeya Settem– G01512992

# Kubernetes Secret storing sensitive database connection details for the backend service.

apiVersion: v1
kind: Secret
metadata:
  name: survey-backend-secrets
  namespace: student-survey
type: Opaque
stringData:
  
  DB_DRIVER: mysql+pymysql
  DB_HOST: student-surveys.ch4ezyusbvcp.us-east-1.rds.amazonaws.com
  DB_PORT: "3306"
  DB_USER: survey_user
  DB_PASSWORD: survey_password_2025
  DB_NAME: student_surveys
