# Team members:
# 1. Anusha Gurram – G01514835
# 2. Bala Naga Tirumala Kiran Annadata – G01508483
# 3. Yashwanth Karthikeya Settem– G01512992

# Kubernetes ConfigMap providing environment variables and DB settings for the backend service.

apiVersion: v1
kind: ConfigMap
metadata:
  name: survey-backend-config
  namespace: student-survey
data:
  ENVIRONMENT: production
  SQL_ECHO: "false"
  DB_POOL_SIZE: "5"
  DB_POOL_MAX_OVERFLOW: "10"
  DB_POOL_RECYCLE: "1800"
  # Allow the frontend origin by IP (no TLS yet)
  CORS_ORIGINS: '["http://54.144.119.218:30081"]'
