# Team members:
# 1. Anusha Gurram – G01514835
# 2. Bala Naga Tirumala Kiran Annadata – G01508483
# 3. Yashwanth Karthikeya Settem– G01512992

# ConfigMap that provides the frontend’s runtime configuration file used to set API URL and timeout.

apiVersion: v1
kind: ConfigMap
metadata:
  name: survey-frontend-config
  namespace: student-survey
data:
  runtime-config.js: |
    window.__SURVEY_CONFIG__ = {
      apiBaseUrl: "http://54.89.180.214:30080/api",
      apiTimeoutMs: 15000,
    };
