# Team members:
# 1. Anusha Gurram – G01514835
# 2. Bala Naga Tirumala Kiran Annadata – G01508483
# 3. Yashwanth Karthikeya Settem– G01512992

# Creates the dedicated Kubernetes namespace for all Student Survey resources.

apiVersion: v1
kind: Namespace
metadata:
  name: student-survey

